name: Checkout
on : [push]
jobs:
    checkout-with-actions:
        runs-on: ubuntu-latest
        steps:
            - name: List files before checkout
              run: ls -al
            - name: checkout-with-actions
              uses: actions/checkout@v4
            - name: List files after action-checkout Completed.
              run: ls -al
    # checkout:
    #     runs-on: ubuntu-latest
    #     needs: checkout-with-actions
    #     steps:
    #         - name: List files before checkout
    #           run: ls -al
    #         - name: checkout-repository
    #           run: |
    #             git init
    #             git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
    #             git fetch origin
    #             git checkout main
    #         - name: List files after checkout-complete
    #           run: ls -al
    #         - name: Show current branch
    #           run: git branch