name: My First Workflow
on: [push]
jobs:
    run-a-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: Runs a shell command
            run: echo "Hello World"
          - name: Runs multiple shell commands.
            run: |
              node -v
              npm -v
              cat /etc/os-release
          - name: Runs multiple commnds with >
            run: >      
                echo "Hello Rakesh" > Hello.txt
                cat Hello.txt
    run-a-parallel-job:
      runs-on: macos-latest
      steps: 
        - name: Runs a shell commad in macOS
          run: sw_vers -productVersion
    run-a-dependent-job:
      needs: run-a-shell-command
      runs-on: windows-latest
      steps:
        - name: Runs a windows shell command
          run: |
            echo : "Hello from Windows"
            Write-Output "Hello from Rakesh"
        - name: Error Step
          run: |
            echo "This step will fail"
            exit 1
